apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {APPNAME}
  name: {CI_PROJECT_NAME}
  namespace: austral
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {APPNAME}
  template:
    metadata:
      labels:
        app: {APPNAME}
    spec:
      containers:
          image: 'us.gcr.io/{PROJECTID}/{CI_PROJECT_NAME}:{VERSION}'
          name: {APPNAME}
          ports:
            - containerPort: 8080
              name: "http"
              protocol: "TCP"
          livenessProbe:
            httpGet:
              path: /info/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            limits:
              cpu: "512m"
              memory: "750Mi"
            requests:
              cpu: "128m"
              memory: "250Mi"
