apiVersion: "v1"
kind: "Service"
metadata:
  name: "{CI_PROJECT_NAME}-service"
  namespace: "austral"
  labels:
    app: "{APPNAME}"
spec:
  ports:
    - protocol: "TCP"
      port: 8080
  selector:
    app: "{APPNAME}"
  type: "ClusterIP"
