## Ci/CD para los desarollos de Python 3x en NSR en GitLab

stages:
  - validate-version
  - build
  - clair
  - publish
  - clean
  - deploy

include:
  - project: 'nsr/pipeline-template'
    ref: envgonsul
    file: 'python.yml'
